--- insumos agricolas

-- Agregar unidades de medida faltantes
INSERT INTO unidad_medida (nombre, abreviatura, categoria_id) VALUES
('Bolsa 60000 semillas', 'bolsa 60k sem', 
 (SELECT id FROM categoria_unidad_medida WHERE nombre = 'Volumen')),
('Bulto 50 kilogramos', 'bulto 50kg', 
 (SELECT id FROM categoria_unidad_medida WHERE nombre = 'Masa'));

 -- Insertar categorías de insumos agrícolas
INSERT INTO categoria_insumo_agricola (nombre, descripcion) VALUES
('Fertilizantes', 'Insumos para nutrición y fertilización del cultivo de maíz'),
('Fungicidas', 'Insumos para control de enfermedades fúngicas'),
('Insecticidas', 'Insumos para control de plagas e insectos'),
('Herbicidas', 'Insumos para control de malezas'),
('Semillas', 'Material genético certificado para siembra'),
('Acondicionadores de Suelo', 'Insumos para mejorar las condiciones del suelo'),
('Otros Insumos', 'Insumos complementarios para el manejo del cultivo');

-- Insertar insumos agrícolas
INSERT INTO insumo_agricola (categoria_id, nombre, descripcion, unidad_medida_id, costo_unitario, stock_actual) VALUES
-- Fertilizantes
((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Fertilizantes'),
 'Urea 46-0-0',
 'Fertilizante nitrogenado granular para desarrollo vegetativo',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'bulto 50kg'),
 180000,
 125),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Fertilizantes'),
 'DAP 18-46-0',
 'Fosfato Diamónico para desarrollo radicular',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'bulto 50kg'),
 195000,
 125),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Fertilizantes'),
 'KCl 0-0-60',
 'Cloruro de Potasio para llenado de grano',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'bulto 50kg'),
 165000,
 125),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Fertilizantes'),
 'Nutrimon 15-15-15',
 'Fertilizante compuesto NPK balanceado para etapas iniciales',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'bulto 50kg'),
 160000,
 125),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Fertilizantes'),
 'Abocol Triple 15',
 'Fertilizante granular balanceado para desarrollo general',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'bulto 50kg'),
 155000,
 125),

-- Fungicidas
((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Fungicidas'),
 'Mole SC325',
 'Fungicida sistémico para control de enfermedades foliares en maíz',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'L'),
 180000,
 45),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Fungicidas'),
 'Nativo SC300',
 'Fungicida de amplio espectro para control de roya y tizón',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'L'),
 195000,
 45),

-- Silvacur Combi EC300
((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Fungicidas'),
 'Silvacur Combi EC300',
 'Fungicida preventivo y curativo para enfermedades foliares',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'L'),
 170000,
 45),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Fungicidas'),
 'Mancozeb 80 WP',
 'Controla hongos como roya, mildiu y mancha de hoja',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'kg'),
 27500,
 45),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Fungicidas'),
 'Carbendazim CRL 500 SC',
 'Fungicida sistémico preventivo y curativo',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'L'),
 55000,
 45),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Fungicidas'),
 'Amistar Top',
 'Fungicida sistémico de Syngenta para control de complejo mancha de asfalto',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'L'),
 280000,
 45),

-- Insecticidas
((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Insecticidas'),
 'Audax FS600',
 'Insecticida para tratamiento de semillas',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'L'),
 280000,
 35),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Insecticidas'),
 'Belt SC480',
 'Control de lepidópteros en cultivos de maíz',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'L'),
 320000,
 35),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Insecticidas'),
 'Connect Duo OD300',
 'Insecticida de amplio espectro para control de plagas',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'L'),
 185000,
 35),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Insecticidas'),
 'Destello SC',
 'Control de gusano cogollero y barrenadores',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'L'),
 145000,
 35),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Insecticidas'),
 'Dinastia EC100',
 'Insecticida piretroide para control de plagas',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'L'),
 98000,
 35),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Insecticidas'),
 'Dipel WG6,4',
 'Insecticida biológico para control de orugas',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'kg'),
 125000,
 35),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Insecticidas'),
 'Lorsban 4EC',
 'Insecticida organofosforado de amplio espectro',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'L'),
 65000,
 35),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Insecticidas'),
 'Lambda-cihalotrina',
 'Controla gusanos e insectos chupadores',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'L'),
 25000,
 35),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Insecticidas'),
 'Engeo',
 'Insecticida de Syngenta para control de cogollero y chinches',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'L'),
 195000,
 35),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Insecticidas'),
 'Fiprogent',
 'Insecticida de contacto para control de cogollero y gusanos',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'L'),
 145000,
 35),

-- Herbicidas
((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Herbicidas'),
 'Roundup Activo',
 'Herbicida sistémico de amplio espectro',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'L'),
 45000,
 85),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Herbicidas'),
 'Roundup Brio',
 'Herbicida post-emergente para control de malezas',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'L'),
 42000,
 85),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Herbicidas'),
 'Atrazina Vecol 90 WG',
 'Herbicida selectivo pre y post emergente',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'kg'),
 45000,
 85),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Herbicidas'),
 'Glifosato Roundup 480 SL',
 'Herbicida sistémico no selectivo',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'L'),
 38000,
 85),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Herbicidas'),
 'Pendimetalina Vecol 400 EC',
 'Herbicida pre-emergente, evita el crecimiento de malezas desde la semilla',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'L'),
 32500,
 85),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Herbicidas'),
 'Amina 720 SL',
 'Herbicida hormonal selectivo para control de malezas de hoja ancha',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'L'),
 35000,
 85),

-- Semillas
((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Semillas'),
 'AGROSAVIA V-117',
 'Maíz amarillo de doble propósito (grano y silo), rústico con buen porte y sistema radicular. Adaptado a la región Caribe húmeda',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'bolsa 60k sem'),
 750000,
 12),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Semillas'),
 'AGROSAVIA V-160 QPM',
 'Variedad de maíz blanco con alto contenido de lisina. Recomendado para Valles del Sinú y sabanas de Córdoba, Sucre y Bolívar',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'bolsa 60k sem'),
 780000,
 12),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Semillas'),
 'AGROSAVIA V-121',
 'Maíz amarillo de doble propósito adaptado a la región Caribe húmeda, especialmente Valle del Sinú y sabanas',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'bolsa 60k sem'),
 750000,
 12),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Semillas'),
 'AGROSAVIA V-116 HAWAII DULCE',
 'Maíz dulce amarillo, susceptible al gusano cogollero y Cercospora zeae-maydis pero mínimamente afectado',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'bolsa 60k sem'),
 820000,
 12),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Semillas'),
 'CORPOICA V-114',
 'Variedad de maíz amarillo',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'bolsa 60k sem'),
 720000,
 12),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Semillas'),
 'CORPOICA V-115 Dulce',
 'Variedad de maíz dulce amarillo, susceptible al gusano cogollero y Cercospora zeae-maydis',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'bolsa 60k sem'),
 800000,
 12),

-- Continuación Semillas
((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Semillas'),
 'CORPOICA V-159',
 'Variedad de maíz blanco',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'bolsa 60k sem'),
 720000,
 12),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Semillas'),
 'HR-ORO',
 'Híbrido de maíz amarillo apto para grano y silo, excelente forraje con alta calidad nutricional',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'bolsa 60k sem'),
 850000,
 12),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Semillas'),
 'ICA V-305',
 'Variedad de maíz amarillo duro de porte medio, uniforme, con buen vigor, estabilidad y alto potencial de rendimiento',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'bolsa 60k sem'),
 720000,
 12),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Semillas'),
 'ICA V-109',
 'Maíz amarillo para grano o silo',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'bolsa 60k sem'),
 700000,
 12),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Semillas'),
 'ICA-V 156',
 'Variedad de maíz blanco para grano o silo',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'bolsa 60k sem'),
 700000,
 12),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Semillas'),
 'SGBIOH2',
 'Híbrido de maíz biofortificado con alto contenido de zinc, desarrollado por CIMMYT para reducir la malnutrición en Colombia',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'bolsa 60k sem'),
 880000,
 12),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Semillas'),
 'Pioneer P3966',
 'Híbrido de maíz amarillo de alto rendimiento para zona cafetera y valles interandinos',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'bolsa 60k sem'),
 920000,
 12),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Semillas'),
 'Dekalb DK7088',
 'Híbrido de maíz amarillo tecnología VT Triple Pro para control de plagas',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'bolsa 60k sem'),
 980000,
 12),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Semillas'),
 'DK 7088',
 'Híbrido amarillo de alto rendimiento',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'bolsa 60k sem'),
 850000,
 12),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Semillas'),
 'P30F35',
 'Híbrido blanco tolerante a sequía',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'bolsa 60k sem'),
 820000,
 12),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Semillas'),
 'FNC 318',
 'Variedad mejorada de polinización abierta',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'kg'),
 25000,
 12),

-- Acondicionadores de Suelo
((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Acondicionadores de Suelo'),
 'Cal Agrícola Dolomita BM',
 'Ajusta el pH del suelo, mejora absorción de nutrientes',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'bulto 50kg'),
 20000,
 200),

-- Otros Insumos
((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Otros Insumos'),
 'Cosmo-Aguas',
 'Coadyuvante para aplicación de agroquímicos',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'L'),
 28000,
 65),

((SELECT id FROM categoria_insumo_agricola WHERE nombre = 'Otros Insumos'),
 'Nutrifoliar Completo',
 'Fertilizante foliar multinutrientes',
 (SELECT id FROM unidad_medida WHERE abreviatura = 'L'),
 45000,
 65);
